# SPDX-FileCopyrightText: 2025 Sequent Tech Inc <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

openapi: 3.0.0
info:
  title: Sequent Integration Endpoints for Datafix VoterView
  description: >-
    This document provides detailed guidelines for third-party integration with Sequent endpoints, covering headers, authentication, request bodies, URL parameters, and response formats.

    Authentication and authorization are managed via a client-id and client-secret, sent in the Authorization header. In Swagger, you can configure these credentials using the "Authorize" button. The Sequent endpoint uses these credentials to request and manage the access token from Keycloak.

    The integration environment (testing or production) is determined by the tenant-id specified in the headers, while the event-id remains static for each municipality across all environments and tenants.

    Sequent will provide the tenant-id, and the event-id corresponds to the MUNCODE configured in Datafix.
  version: 1.0.0
  contact:
    name: Sequent Tech Support
    email: support@sequentech.io
  license:
    name: AGPL-3.0-only
    url: https://spdx.org/licenses/AGPL-3.0-only.html
servers:
  - url: https://{customerId}.sequent.vote
    variables:
      customerId:
        default: staiging
        description: Customer ID assigned by the service provider
tags:
  - name: API
    description: Datafix Endpoints
    externalDocs:
      description: Find out more
      url: >-
        https://github.com/sequentech/step/blob/feat/meta-5407/main/docs/datafix-integration/sequent-endpoints.md
paths:
  /api/datafix/delete-voter:
    post:
      summary: Delete a voter
      description: Marks the voter as disabled in the Sequent system.
      tags:
        - API
      parameters:
        - name: tenant-id
          in: header
          required: true
          schema:
            type: string
          description: Realm ID for Keycloak’s endpoint
        - name: event-id
          in: header
          required: true
          schema:
            type: string
          description: >-
            Unique for each election event, matches Datafix ID in election event
            annotations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                voter_id:
                  type: string
                  description: Unique ID of the voter to be deleted.
              required:
                - voter_id
      responses:
        '200':
          description: Action completed successfully
          content:
            application/json:
              example:
                code: '200'
                message: Success
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                code: '400'
                message: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                code: '401'
                message: Unauthorized
        '404':
          description: Voter does not exist
          content:
            application/json:
              example:
                code: '404'
                message: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                code: '500'
                message: InternalServerError
      security:
        - ApiKeyAuth: []

  /api/datafix/add-voter:
    post:
      summary: Add a new voter
      description: Adds a new voter to the system with the specified details.
      tags:
        - API
      parameters:
        - name: tenant-id
          in: header
          required: true
          schema:
            type: string
          description: Realm ID for Keycloak’s endpoint
        - name: event-id
          in: header
          required: true
          schema:
            type: string
          description: >-
            Unique for each election event, matches Datafix ID in election event
            annotations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                voter_id:
                  type: string
                  description: Unique ID of the voter.
                ward:
                  type: string
                  description: Ward or area of the voter.
                schoolboard:
                  type: string
                  description: Schoolboard (optional).
                poll:
                  type: string
                  description: Poll area (optional).
                birthdate:
                  type: string
                  format: date
                  description: >-
                    Birthdate of the voter (optional). - ISO 8601 format
                    YYYY-MM-DD
              required:
                - voter_id
                - ward
      responses:
        '200':
          description: Action completed successfully
          content:
            application/json:
              example:
                code: '200'
                message: Success
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                code: '400'
                message: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                code: '401'
                message: Unauthorized
        '404':
          description: Voter does not exist
          content:
            application/json:
              example:
                code: '404'
                message: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                code: '500'
                message: InternalServerError
      security:
        - ApiKeyAuth: []

  /api/datafix/update-voter-information:
    post:
      summary: Update voter information
      description: Updates the details of an existing voter in the system.
      tags:
        - API
      parameters:
        - name: tenant-id
          in: header
          required: true
          schema:
            type: string
          description: Realm ID for Keycloak’s endpoint
        - name: event-id
          in: header
          required: true
          schema:
            type: string
          description: >-
            Unique for each election event, matches Datafix ID in election event
            annotations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                voter_id:
                  type: string
                  description: Unique ID of the voter.
                ward:
                  type: string
                  description: Ward or area of the voter.
                schoolboard:
                  type: string
                  description: Schoolboard (optional).
                poll:
                  type: string
                  description: Poll area (optional).
                birthdate:
                  type: string
                  format: date
                  description: >-
                    Birthdate of the voter (optional) - ISO 8601 format
                    YYYY-MM-DD.
              required:
                - voter_id
                - ward
      responses:
        '200':
          description: Action completed successfully
          content:
            application/json:
              example:
                code: '200'
                message: Success
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                code: '400'
                message: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                code: '401'
                message: Unauthorized
        '404':
          description: Voter does not exist
          content:
            application/json:
              example:
                code: '404'
                message: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                code: '500'
                message: InternalServerError
      security:
        - ApiKeyAuth: []

  /api/datafix/mark-voted:
    post:
      summary: Mark voter as voted
      description: Marks a voter as having cast their vote through a specified channel.
      tags:
        - API
      parameters:
        - name: tenant-id
          in: header
          required: true
          schema:
            type: string
          description: Realm ID for Keycloak’s endpoint
        - name: event-id
          in: header
          required: true
          schema:
            type: string
          description: >-
            Unique for each election event, matches Datafix ID in election event
            annotations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                voter_id:
                  type: string
                  description: Unique ID of the voter.
                channel:
                  type: string
                  description: >-
                    Channel through which the voter cast their vote, e.g.,
                    online, in-person, postal.
              required:
                - voter_id
                - channel
      responses:
        '200':
          description: Action completed successfully
          content:
            application/json:
              example:
                code: '200'
                message: Success
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                code: '400'
                message: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                code: '401'
                message: Unauthorized
        '404':
          description: Voter does not exist
          content:
            application/json:
              example:
                code: '404'
                message: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                code: '500'
                message: InternalServerError
      security:
        - ApiKeyAuth: []

  /api/datafix/unmark-voted:
    post:
      summary: UnMark voter as voted
      description: Marks a voter as having cast their vote through a specified channel.
      tags:
        - API
      parameters:
        - name: tenant-id
          in: header
          required: true
          schema:
            type: string
          description: Realm ID for Keycloaks endpoint
        - name: event-id
          in: header
          required: true
          schema:
            type: string
          description: >-
            Unique for each election event, matches Datafix ID in election event
            annotations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                voter_id:
                  type: string
                  description: Unique ID of the voter.
              required:
                - voter_id
      responses:
        '200':
          description: Action completed successfully
          content:
            application/json:
              example:
                code: '200'
                message: Success
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                code: '400'
                message: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                code: '401'
                message: Unauthorized
        '404':
          description: Voter does not exist
          content:
            application/json:
              example:
                code: '404'
                message: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                code: '500'
                message: InternalServerError
      security:
        - ApiKeyAuth: []

  /api/datafix/replace-pin:
    post:
      summary: Replace voter PIN
      description: Replaces or generates a new PIN for the specified voter.
      tags:
        - API
      parameters:
        - name: tenant-id
          in: header
          required: true
          schema:
            type: string
          description: Realm ID for Keycloak’s endpoint
        - name: event-id
          in: header
          required: true
          schema:
            type: string
          description: >-
            Unique for each election event, matches Datafix ID in election event
            annotations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                voter_id:
                  type: string
                  description: Unique ID of the voter.
              required:
                - voter_id
      responses:
        '200':
          description: Action completed successfully
          content:
            application/json:
              example:
                code: '200'
                message: Success
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                code: '400'
                message: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                code: '401'
                message: Unauthorized
        '404':
          description: Voter does not exist
          content:
            application/json:
              example:
                code: '404'
                message: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                code: '500'
                message: InternalServerError
      security:
        - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: >-
            Client ID and Client secret Respectively. Formatauthorization:123456:987654

security:
  - ApiKeyAuth: []